#!/bin/bash

if [ "$1" == "cpp" ]; then
    cat << EOF > main.cpp
#include <bits/stdc++.h>
using namespace std;

int main() {
    // Your code here

    return 0;
}
EOF
elif [ "$1" == "py" ]; then
    cat << EOF > main.py
# Your code here
EOF
else
    echo "Usage: gen_boilerplate <cpp|py>"
fi

